params:  
  diff_env:
    name: TrafficSinglePaceCarEnv_E
    stochastic_env: True
    episode_length: 1000
    MM_caching_frequency: 16

  algo:
    name: grad_a2c_continuous

  load_checkpoint: False
  load_path: nn/df_traffic_pace_car.pth

  # load_checkpoint: True
  # load_path: ./examples/logs/ackley/grad_ppo/01-18-2023-11-16-13/nn/df_ackley.pth

  config:
    device: 'cpu'
    name: df_traffic_pace_car_grad_ppo
    env_name: dflex
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: False
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
   
    score_to_win: 20000
    max_epochs: 500
    save_best_after: 50
    save_frequency: 100
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    steps_num: 32          # useless
    num_actors: 64
    minibatch_size: 2048
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001

    # LEARNING RATE FOR PPO UPDATE;
    # Keep [lr_schedule] to be "adaptive", and change [lr_threshold] and [kl_threshold]
    # to speficy desired KL div between updated policies;
    learning_rate: 3e-4
    lr_schedule: adaptive
    lr_threshold: 0.008
    kl_threshold: 0.008

    # grad informed

    defer_summaries_sec: 0.001
    summaries_interval_sec_min: 0.001
    summaries_interval_sec_max: 0.002
    
    gi_params:
      
      num_step: 32

      # THESE ARE THE REAL NETWORKS WE ARE GOING TO USE;
      network:
        actor: ActorStochasticMLP # ActorDeterministicMLP
        actor_mlp:
          units: [512, 64, 64]
          activation: elu
        actor_logstd_init: 0.0

        critic: CriticMLP
        critic_mlp:
          units: [64, 64]
          activation: elu

      lr_schedule: linear # [constant, linear]
      
      # LEARNING RATE FOR SHAC ACTOR UPDATE;
      actor_learning_rate: 1e-3

      # LEARNING RATE FOR SHAC CRITIC UPDATE;
      critic_learning_rate: 1e-3
      critic_iterations: 16
      critic_num_batch: 4
      target_critic_alpha: 0.2
      
      betas: [0.7, 0.95] # adam
    
    player:
      # render: True
      determenistic: True
      games_num: 12
      num_actors: 4
      print_stats: True

  # Useless settings ========================================
  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None